module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-case": [2, "always", "lower-case"],
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
    "scope-empty": [2, "never"],
    "scope-enum": [
      2,
      "always",
      [
        "frontend",
        "api",
        "auth",
        "db",
        "model",
        "data",
        "strategy",
        "broker",
        "risk",
        "core",
        "infra",
        "config",
        "ci",
        "cd",
        "docs",
        "deps",
        "repo",
      ],
    ],
  },
};
